---
title: Cyanobacteria Monitoring Collaborative - Participants
output: html_document
---

```{r, echo=FALSE,message=FALSE,warning=FALSE}
#Set up DT from the csv
#
# sudo rm libstdc++.so.6
# sudo ln -s /usr/bin/gcc-4.6.2/lib64/libstdc++.so.6.0.20 libstdc++.so.6
library(magick)
library(dplyr)
library(knitr)

cmc <- read.csv("cmc_partners_2016_09_09_cleaned.csv", 
                stringsAsFactors = FALSE, strip.white = TRUE) %>%
  filter(Logo != "logos/NA",
         Web != "?")
for(i in cmc$Logo){
  l <- image_read(i)
  l_s <- image_scale(l,"x50")
  image_write(l_s,paste0("logos/resize/",gsub("logos/","",i)))
}

name <- paste0("[",cmc$Organization,"]","(",cmc$Web,")")
logo <- paste0("![",cmc$Organization,"]","(logos/resize/",gsub("logos/","",cmc$Logo),")")
xdf <- data.frame(Logo = logo, Organization = name, State = cmc$State)
names(xdf)[1] <-c(" ")
```

```{r,echo=FALSE,results='asis'}
kable(xdf)
```

```{r datatable, echo=FALSE}
library(DT)
library(commonmark)
for(i in seq_along(name)){
  name[i]<-markdown_html(name[i])
}
for(i in seq_along(logo)){
  logo[i]<-markdown_html(logo[i])
}
xdf <- data.frame(Logo = logo, Organization = name, State = cmc$State)
datatable(xdf, escape = FALSE,rownames = FALSE, 
          options = list(pageLength = nrow(xdf),
                         dom = "ft")) %>%
  htmlwidgets::saveWidget("partners.html", selfcontained = TRUE)
```